apiVersion: v1
kind: Pod
metadata:
  name: conf-pod
spec:
  containers:
    - name: tomcat
      image: tamcat
      env:
      - name: course
        valueFrom:
          configMapKeyRef:
            name: course-config
            key: course
      - name: duration
        valueFrom:
          configMapKeyRef:
            name: course-config
            key: duration


