apiVersion: v1
kind: Pod
metadata:
  name: probe
spec:
  containers:
  - image: tomcat
    name: tomcat
  livenessProbe:
    httpGet:
      path: /
      port: 80
      initialDelaySeconds: 3
      periodSeconds: 5
