apiVersion: v1
kind: Pod
metadata:
  name: limits-requsts
  namespace: roboshop
spec:
  containers:
  - image: tomcat
    name: tomcat
    ports:
      containePort:80
    resources:
      requests:
        cup: "200m"
        memory: "150mi"
      limits:
        cpu: "500m"
        memory: "250mi"