apiVersion: v1
kind: Pod
metadata:
  name: multi
spec:
  containers:
    - image: nginx:1.14.2
      name: nginx
      ports:
        - containerPort: 80
    - image: almalinux
      name: sidecar
      #command: ["sleep","100"]