apiVersion: v1
kind: Pod
metadata:
  name: secrets-pod
spec:
  containers:
    - name: tomcat
      image: tomcat
      env:
        - name: USERNAME
          valueFrom:
             secretKeyRef:
              name: mysecret
              key: username
        - name: PASSWORD
          valueFrom:
             secretKeyRef:
              name: mysecret
              key: password