---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    server: tomcat
spec:
  containers:
  - name: tomcat
    image: tomcat
    ports:
     containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-pod
spec:
  selector:
    server: tomcat
  ports:
    - protocal: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  labels:
  purpose: debug
spec:
  containers:
    name: almalinux
    image: almalinux
    command: ["sleep","500"]