---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    name: tomcat
spec:
  containers:
  - name: tomcat
    image: tomcat
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-pod
spec:
  selector:
    name: tomcat
  ports:
    - protocal: TCP
      port: 80
      targetPort: 80